name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-manylinux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: python -m pip install -U pip setuptools

      - name: Build manylinux Python wheels
        uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux2010_x86_64
        with:
          python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38m cp39-cp39m'
          build-requirements: 'setuptools pybind11'
          pip-wheel-args: '-w ./dist --no-deps --no-use-pep517'
